Repository fga-eps-mds/2021.2-Sigaa-Plus, pull requests merged in 2022-03, with the labels that each got.

#107 [DOC] (Issue #105) : Criação do documento do roadmap
  docs/DocumentoDoRoadmap.md
Labels: Time A, Documentation, Product Owner

#109 [ADD] (Issue #105) : Adicionando imagem do Roadmap
  docs/DocumentoDoRoadmap.md
Labels: Time A, Documentation, Product Owner

#111 [FIX] (Issue #91) : Concertando erros na estrutura do documento
  docs/DocumentoDeVisao.md
Labels: Time A, Documentation, Product Owner

#114 [FIX] (Issue #112) : Edição do documento de visão
  docs/DocumentoDeVisao.md
Labels: Time A, Documentation, Product Owner

#117 [DOC] (Issue #113): Abertura do documento de ferramentas utilizadas
  docs/Ferramentas.md
Labels: Time B, Documentation, Scrum Master

#123 [DOC] (Issue #120): Atualizando Termo de Abertura do Projeto
  docs/TAP.md
Labels: Time B, Documentation, Scrum Master

#125 [DOC] (Issue #118) : adição de conteúdo nos tópicos 4, 5 e 6
  docs/DocumentoDeMetodologia.md
Labels: Time B, Documentation, Arquiteto

#127 [ADD] issue #119: realizando webscraping na pagina publica do sigaa e…
  api/services/scraping/equivalencias.json
  api/services/scraping/webScraping.js
  package-lock.json
  package.json
Labels: back-end, Time A

#128 [DOC] issue #122: adição de conteúdos nos tópicos 1, 2 e 3
  docs/DocumentoDeMetodologia.md
Labels: Documentation, Arquiteto

#129 Backlog
  docs/BacklogDoProduto.md
Labels: Time B, Documentation, Product Owner

#131 Feature modelo Canvas
  docs/modeloCanvas.pdf
Labels: Documentation, Product Owner, Feature

#130 Feature doc prototipo
  docs/Prototipo.md
  docs/assets/images/FluxoUser.png
  docs/assets/images/prototipoBaixaFidelidade-tela1.png
  docs/assets/images/prototipoBaixaFidelidade-tela2.png
  docs/assets/images/prototipoBaixaFidelidade-tela3.png
  docs/assets/images/prototipoBaixaFidelidade-tela4.png
Labels: Time B, Documentation, Product Owner

#132 UPDATE (pull request #115): Atualização das fontes de receita
  docs/modeloCanvas.png
Labels: Time A, Documentation, Product Owner

#135 FIX (pull-request #132): modificação de branch destino
  docs/modeloCanvas.pdf
Labels: bug

#138 Funcionalidade pesquisa de equivalências
  api/routes/routes.js
  package-lock.json
  package.json
  src/App.vue
  src/assets/logoSigaaPlus.png
  src/components/tela.vue
Labels: back-end, front-end, Time A, Feature

#153 [DOC] (Issue #https://github.com/fga-eps-mds/2021.2-Sigaa-Plus/issues…
  docs/sprints/sprint7/TimeA/listaPresença.md
  docs/sprints/sprint7/TimeA/planejamento.md
  docs/sprints/sprint7/TimeB
Labels: Time A, team organization, Documentation, Scrum Master

#156 [DOC] (Issue #148): Planejamento Sprint 7 - Time B
  docs/sprints/sprint7/Time B/Planejamento.md
  docs/sprints/sprint7/TimeB
Labels: Time B, team organization, Documentation, Scrum Master

#158 [FIX] (Issue #157) : Especificando usuário do produto
  docs/DocumentoDeRequisitos.md
  docs/DocumentoDeVisao.md
Labels: Time A, Documentation, Product Owner, fix

#161 [DOC] (Issue #152): Atualização do plano de comunicação do Projeto
  docs/DocumentoDeComunicação.md
  docs/DocumentoDeMetodologia.md
Labels: back-end, Documentation

#163 [DOC] (issue #149): atualizando informações sobre ambiente de desenv…
  README.md
Labels: Documentation

#171 [DOC] (Issue #150) : add: Review Sprint 07 Time A
  docs/sprints/sprint7/TimeA/Planejamento.md
  docs/sprints/sprint7/TimeA/Resultado.md
  docs/sprints/sprint7/TimeA/listaPresença.md
Labels: Time A, team organization, Documentation

#168 [DOC] (Issue #164) : Planejamento da Sprint 08 junto ao quadro de prese…
  docs/sprints/sprint7/TimeA/Planejamento.md
  docs/sprints/sprint8/TimeA/planejamento.md
Labels: back-end, Time A, team organization, Documentation

#176 [DOC](Issue #106): planejamento pendente da Sprint 06
  docs/sprints/sprint6/TimeA/planejamento.md
Labels: Documentation, Scrum Master

#175 [DOC] (Issue #173): Realizando documentação pendente da Sprint 6
  docs/sprints/sprint6/Time B/Planejamento.md
  docs/sprints/sprint6/Time B/Resultado.md
Labels: Time B, Documentation, Scrum Master

#174 [DOC] (Issue #162): Resultado Sprint 7
  docs/assets/images/BurnDownSprint7TimeB.png
  docs/assets/images/CumulativeFlowSprint7TimeB.png
  docs/sprints/sprint7/Time B/Resultado.md
  package-lock.json
  package.json
Labels: Time B, Documentation, Scrum Master

#179 Componentes style guide
  StyleGuide.md
Labels: Time B, team organization, Documentation, style

#181 Style guide - tópico "2. Detalhes e motivos"
  StyleGuide.md
  docs/assets/images/paleta.png
Labels: front-end, Time B, Documentation, Arquiteto, style

#183 Feature RF01
  api/services/scraping/equivalencias.json
  api/services/scraping/webScraping.js
  package.json
Labels: back-end, Time A, Feature

#190 [DOC] (Issue #185): Slide de apresentação do Style Guide
  docs/StyleGuide.md
Labels: front-end, Time B, Documentation, Product Owner, style

#191 [DOC] (Issue #169): Documentação Sprint 8 - Time B"
  docs/assets/images/BurnDownSprint8TimeB.png
  docs/assets/images/CumulativeFlowSprint8TimeB.png
  docs/sprints/sprint8/Time B/Planejamento.md
  docs/sprints/sprint8/Time B/Resultado.md
Labels: Time B, team organization, Documentation, Scrum Master

#207 Prototipo alta fidelidade com visão do Google
  docs/Prototipo.md
  docs/assets/images/Tela_5.png
Labels: front-end, Time B, Product Owner, style

#208 [DOC](issue #192): planejamento da Sprint 09
  docs/sprints/sprint9/TimeA/Planejamento.md
Labels: Time A, Documentation, Scrum Master

#230 Feature desenvolvimento inicial da RF03
  package-lock.json
  src/App.vue
  src/assets/128logoSigaaPlus.png
  src/assets/16logoSigaaPlus.png
  src/assets/48logoSigaaPlus.png
  src/components/graficoRF3.vue
  src/components/tela.vue
  src/details/Contentscript.js
  src/details/popup.html
  src/manifest.json
Labels: front-end, Time B, development

#211 [DOC] (Issue #196): Documentação Sprint 9 - Time B
  docs/assets/BurnDownSprint9TimeB.png
  docs/assets/CumulativeFlowSprint9TimeB.png
  docs/sprints/sprint9/TimeA/Time B/Planejamento.md
  docs/sprints/sprint9/TimeA/Time B/Resultado.md
Labels: Time B, Documentation, Scrum Master

#233 Documentacao sprint10
  docs/sprints/sprint10/Time A/Planejamento.md
Labels: Time A, team organization

#234 [UPDATE](Issue #227 #231): api integração do Back-end
  api/routes/routes.js
Labels: back-end, Time A, development
