Repository fga-eps-mds/2021.2-Sigaa-Plus, pull requests merged in 2022-04, with the labels that each got.

#235 Suporte ao front-end para a criação de componentes visuais referentes à RF2.
  src/App.vue
  src/components/telaRF2.vue
Labels: back-end, front-end, Time A, Time B, development

#239 [DOC] (Issue #172 #212 #213): Documentação Pendente
  docs/EstruturaAnalítica.md
  docs/assets/eap.png
  docs/assets/images/BurnDownSprint10TimeB.png
  docs/assets/images/CumulativeFlowSprint10TimeB.png
  docs/sprints/sprint10/Time B/Planejamento.md
  docs/sprints/sprint10/Time B/Resultado.md
  docs/sprints/sprint9/Time B/Planejamento.md
  docs/sprints/sprint9/Time B/Resultado.md
Labels: Time B, team organization, Documentation, Scrum Master

#240 [ADD] (Issue #214): Desenvolvimento tela de gráficos
  package-lock.json
  src/components/telaGraficos.vue
Labels: front-end, Time B, Feature, development

#241 Suporte ao front-end para a criação de componentes visuais referentes à RF01.
  package-lock.json
  src/App.vue
  src/components/telaRF1_parte1.vue
  src/components/telaRF1_parte2.vue
Labels: back-end, front-end, Time A, Time B, development

#250 [FIX] (Issue #249): Corrigindo css nos componentes visuais
  src/App.vue
  src/components/telaGraficos.vue
  src/components/telaRF1_parte1.vue
  src/components/telaRF1_parte2.vue
  src/components/telaRF2.vue
Labels: bug, front-end, Time B, fix, style, development

#251 Feature review sprint11
  docs/sprints/sprint10/Time A/Resultado.md
  docs/sprints/sprint11/TimeA/Resultado.md
  docs/sprints/sprint9/Time A/Resultado.md
Labels: Documentation, Scrum Master

#255 [#DOC](Issue #253): criação do documento de planejamento da Sprint 12
  docs/sprints/sprint12/TimeA/Planejamento.md
Labels: Time A, Documentation

#271 [FIX] (Issue #228) : criando botão
  api/services/scraping/materiasCursadas.js
Labels: front-end, Time A, Feature

#280 Documentação de sprints pendentes
  docs/sprints/sprint11/TimeB/Planejamento.md
  docs/sprints/sprint11/TimeB/Resultado.md
  docs/sprints/sprint12/TimeB/Planejamento.md
  docs/sprints/sprint12/TimeB/Resultado.md
  docs/sprints/sprint13/TimeB/Planejamento.md
Labels: Time B, Documentation, Scrum Master

#270 [DOC](Issue #261): documento de planejamento da Sprint 13
  docs/sprints/sprint13/Time A/Planejamento.md
Labels: Time A, Documentation

#281 Feature rf01 integracao
  src/components/tela.vue
Labels: Time A, development

#277 Feature review sprint6
  docs/sprints/sprint6/Time A/Planejamento.md
  docs/sprints/sprint6/Time A/Resultado.md
Labels: Time A, Documentation

#275 [REFACT] (Issue #274) : correção e refatoração
  src/components/telaRF2.vue
Labels: front-end, Time A, style

#288 Parte visual da RF02 com atualizações
  api/routes/routes.js
  package-lock.json
  src/components/telaRF2.vue
Labels: front-end, fix

#289 [DOC/FIX]:Adicionando novamente documentação devido a problemas de co…
  docs/DocumentoDeMedicaDeQualidade.md
Labels: Documentation, QA

#290 [UPDATE] (issue #268 #273): Redimensionando componentes para se adequ…
  api/services/scraping/materiasCursadas.js
  src/components/telaGraficos.vue
  src/details/Contentscript.js
  src/manifest.json
  src/materiasCursadas.js
Labels: front-end, Time A, style

#295 [ADD] (Issue: #228) : Comparando materias cursadas
  package-lock.json
  package.json
  src/components/telaRF2.vue
  src/cursoDoUsuario.js
  src/details/Contentscript.js
  src/materiasCursadas.js
Labels: back-end, Time A, DevOps

#292 [DOC](Issue #263): Documentação das Ferramentas de Testes
  docs/Tools_Testing.md
Labels: Documentation

#299 [DOC] (Issue #298): Resultado Sprint 13 - Time B
  api/routes/routes.js
  docs/DocumentoDeConduta.md
  docs/DocumentoDeMedicaDeQualidade.md
  docs/DocumentoDoRoadmap.md
  docs/EstruturaAnalítica.md
  docs/Prototipo.md
  docs/Tools_Testing.md
  docs/assets/BurnDownSprint13TimeB.png
  docs/assets/CumulativeFlowSprint13TimeB.png
  docs/assets/modeloCanvas.md
  docs/sprints/sprint10/Time A/Resultado.md
  docs/sprints/sprint11/TimeA/Resultado.md
  docs/sprints/sprint11/TimeB/Planejamento.md
  docs/sprints/sprint11/TimeB/Resultado.md
  docs/sprints/sprint12/TimeA/Planejamento.md
  docs/sprints/sprint12/TimeA/Resultado.md
  docs/sprints/sprint12/TimeB/Planejamento.md
  docs/sprints/sprint12/TimeB/Resultado.md
  docs/sprints/sprint13/Time A/Planejamento.md
  docs/sprints/sprint13/Time A/Resultado.md
  docs/sprints/sprint13/TimeB/Planejamento.md
  docs/sprints/sprint13/TimeB/Resultado.md
  docs/sprints/sprint6/Time A/Planejamento.md
  docs/sprints/sprint6/Time A/Resultado.md
  docs/sprints/sprint9/Time A/Resultado.md
  package-lock.json
  package.json
  src/App.vue
  src/components/tela.vue
  src/components/telaRF2.vue
  src/cursoDoUsuario.js
  src/details/Contentscript.js
  src/main.js
  src/manifest.json
  src/materiasCursadas.js
Labels: Time B, team organization, Documentation, Scrum Master
