Repository fga-eps-mds/2021.2-Sigaa-Plus, pull requests merged in 2022-02, with the labels that each got.

#25 Documentação de planejamento da sprint 1
  README.md
  docs/TAP.md
  docs/sprints/sprint1/Planejamento.md
Labels: Documentação

#28 #10 Documentando o termo de abertura de projeto
  docs/TAP.md
Labels: Documentação, Scrum Master

#63 FIX (Issue #60): fazendo ajuste na documentação da sprint 2
  docs/sprints/sprint2/Planejamento.md
  docs/sprints/sprint2/Resultado.md
Labels: Documentação, fix

#68 Documento de Requisitos
  docs/DocumentoDeRequisitos.md
Labels: Documentation, Product Owner

#73 [ADD] (Issue #65): Iniciando estrutura analítica do projeto
  docs/EstruturaAnalítica.md
  docs/assets/eap.png
Labels: Time B, Documentation, Scrum Master

#88 ADD (Issue #81): Planejamento da Sprint 05
  docs/sprints/sprint5/TimeA/planejamento.md
  docs/sprints/sprint5/TimeB/planejamento.md
Labels: Time A, Time B, Documentation

#96 [DOC] (Issue #80) : Upload das variações da logo do projeto.
  docs/assets/images/s+ com fundo.jpg
  docs/assets/images/s+ sem fundo.png
  docs/assets/images/sigaa+ com fundo.png
  docs/assets/images/sigaa+ sem fundo.png
Labels: Time A, Documentation, Product Owner

#97 [DOC] Issue #95: Adicionando topicos visão geral,diagrama de pacotes …
  docs/DocumentoDeArquitetura.md
  docs/assets/DiagramaPacotes.svg
  docs/assets/visaoGeralArq.svg
Labels: Time A, Documentation, Arquiteto

#100 [DOC] Issue #98 : add Visão de Casos de Uso
  docs/DocumentoDeArquitetura.md
Labels: Time A, Documentation, Arquiteto

#99 [DOC] issue #93 : atualização do documento de arquitetura
  docs/DocumentoDeArquitetura.md
  docs/assets/images/img_exemploPlugin.png
Labels: Time B, Documentation, Arquiteto
